services:
  wireguard-hub:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-hub
    cap_add:
      - NET_ADMIN
      - SYS_MODULE  # Optional, for kernel modules if needed
    environment:
      # "bash> id=" uid=0(root) gid=0(root) groups=0(root),988(docker)
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - SERVERURL=185.28.22.166
      - SERVERPORT=51820
      - PEERS=spoke1,spoke2,spoke3
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0  # VPN subnet; hub gets .1, spokes get .2+
      - ALLOWEDIPS=0.0.0.0/0  # Routes all spoke traffic (internet + spokes) via hub
      - LOG_CONFS=true  # Logs QR codes/configs for peers
    volumes:
      - ./wg_config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp  # Expose WireGuard port
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1  # Enables IP forwarding for routing
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wg show wg0 | grep -q 'interface: wg0' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  wg_spoke_1:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wg_spoke_1
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./wg_spoke_1:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      wireguard-hub:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wg show wg0 latest-handshakes | grep -q . || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  spoke_1:
    image: ghcr.io/corentinth/it-tools:latest
    container_name: spoke_1
    network_mode: service:wg_spoke_1
    restart: unless-stopped


  wg_spoke_2:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wg_spoke_2
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./wg_spoke_2:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      wireguard-hub:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wg show wg0 latest-handshakes | grep -q . || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  spoke_2:
    image: ghcr.io/corentinth/it-tools:latest
    container_name: spoke_2
    network_mode: service:wg_spoke_2
    restart: unless-stopped


  wg_spoke_3:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wg_spoke_3
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./wg_spoke_3:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      wireguard-hub:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wg show wg0 latest-handshakes | grep -q . || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  spoke_3:
    image: ghcr.io/corentinth/it-tools:latest
    container_name: spoke_3
    network_mode: service:wg_spoke_3
    restart: unless-stopped
