networks:
  wireguard_network:
    external: true

volumes:
  caddy_data: {}

services:
  wireguard_livekit:
    image: linuxserver/wireguard
    container_name: wireguard_livekit
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./wg_livekit_config:/config  # New config dir
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - wireguard_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wg", "show"]
      interval: 30s
      timeout: 10s
      retries: 3

  caddy:
    image: livekit/caddyl4
    container_name: caddy_livekit
    command: run --config /etc/caddy.yaml --adapter yaml
    restart: unless-stopped
    network_mode: service:wireguard_livekit
    volumes:
      - ./caddy.yaml:/etc/caddy.yaml
      - ./certs:/data
      
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: service:caddy_livekit
    # network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
  redis:
    image: redis:7-alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    network_mode: service:caddy_livekit
    # network_mode: "host"
    volumes:
      - ./redis.conf:/etc/redis.conf
