
networks:
  net:
    external: true
    
services:
  synapse-admin:

    image: ghcr.io/etkecc/synapse-admin:latest

    container_name: admin
    hostname: admin

    volumes:
    - ./testdata/synapse:/config
    - ./testdata/synapse.data:/media-store

    # volumes:
    #   - ./SYN/synapse:/data:rw
    # environment:
    #   SYNAPSE_CONFIG_DIR: /data
    #   SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
            
    networks:
      net:
        ipv4_address: 10.10.120.66
        ipv6_address: fd12:3456:789a::120:66

    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.admin.rule=Host(`admin.landingdev.xyz`)
      - traefik.http.routers.admin.entrypoints=websecure
      - traefik.http.routers.admin.tls=true
      - traefik.http.services.admin.loadbalancer.server.port=80

