
networks:
  net:
    external: true
    
services:
  call:
    image: ghcr.io/element-hq/element-call:sha-9b9c08e
    container_name: call

    restart: unless-stopped

    networks:
      net:
        ipv4_address: 10.10.120.66
        ipv6_address: fd12:3456:789a::120:66

    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost/.well-known/matrix/client"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

    labels:
      - traefik.enable=true
      - traefik.http.routers.call.rule=Host(`call.landingdev.xyz`)
      - traefik.http.routers.call.entrypoints=websecure
      - traefik.http.routers.call.tls=true
      - traefik.http.services.call.loadbalancer.server.port=8080
