networks:
  net:
    external: true

services:
  wellknown:
    image: nginx:latest

    container_name: wellknown

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./SYN/MATRIX/:/usr/share/nginx/html/:ro

    restart: unless-stopped

    networks:
      net:
        ipv4_address: 10.10.120.100
        ipv6_address: fd12:3456:789a::120:100

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/.well-known/matrix/client"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"

      # WELL-KNOWN FILE SERVED WITH CORS headers
      - "traefik.http.middlewares.cors.headers.customresponseheaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.cors.headers.customresponseheaders.Access-Control-Allow-Methods=GET,POST,OPTIONS"
      - "traefik.http.middlewares.cors.headers.customresponseheaders.Access-Control-Allow-Headers=*"

      # WELLKNOWN
      - "traefik.http.routers.well-known.rule=Host(`landingdev.xyz`)  && ( (PathPrefix(`/.well-known/matrix/server`)) || (PathPrefix(`/.well-known/matrix/client`)) )"
      - "traefik.http.routers.well-known.middlewares=cors"
      - "traefik.http.routers.well-known.entrypoints=websecure"
      - "traefik.http.routers.well-known.tls=true"
      - "traefik.http.routers.well-known.service=wellknown-service"
      - "traefik.http.services.wellknown-service.loadbalancer.server.port=80"

      # MATRIXRTC
      - "traefik.http.routers.matrixrtc.rule=Host(`matrixrtc.landingdev.xyz`)"
      - "traefik.http.routers.matrixrtc.middlewares=cors"
      - "traefik.http.routers.matrixrtc.entrypoints=websecure"
      - "traefik.http.routers.matrixrtc.tls=true"
      - "traefik.http.routers.matrixrtc.service=matrixrtc-service"
      - "traefik.http.services.matrixrtc-service.loadbalancer.server.port=80"
