networks:
  wireguard_network:
    external: true

volumes:
  caddy_data: {}

services:
  wireguard_whoami:
    image: linuxserver/wireguard
    container_name: wireguard_whoami
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./wg_whoami_config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - wireguard_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wg", "show"]
      interval: 30s
      timeout: 10s
      retries: 3


  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    depends_on:
      - wireguard_whoami
    network_mode: service:wireguard_whoami
    restart: unless-stopped
