networks:
  net:
    external: true

services:

  eturnal:
    image: ghcr.io/processone/eturnal:latest-alpine

    container_name: eturnal
    hostname: eturnal

    ulimits:
      nofile:
        soft: 65536
        hard: 1048576
        
    restart: unless-stopped
    user: 9000:9000

    ### security options
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true

    networks:
        net:
            ipv4_address: 10.10.20.30
            ipv6_address: fd12:3456:789a::20:30
        
    ### networking options
    ports:
     - 3478:3478/tcp    # STUN/TURN non-TLS
     - 3478:3478/udp    # STUN/TURN non-TLS
     - 49500-49800:49500-49800/udp # TURN relay range

    volumes:
      - ./eturnal.yml:/etc/eturnal.yml:ro
      - ./ZEROSSL.185.28.22.166:/opt/eturnal/tls:ro
      # - ./ZEROSSL.CERTIFICATES:/opt/eturnal/tls:ro
      - ./logs:/opt/eturnal/log/:rw

