networks:
  npm_net:
    external: true
    name: npm_net

services:

  eturnal:
    image: ghcr.io/processone/eturnal:latest-alpine

    container_name: turn
    hostname: turn
    domainname: landingdev.xyz
        
    restart: unless-stopped
    user: 9000:9000

    ### security options
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true

    networks:
        npm_net:
            ipv4_address: 10.10.30.10
            ipv6_address: fd12:3456:789a::30:10

    ### networking options
    ports:
     - 3478:3478/tcp    # STUN/TURN non-TLS
     - 3478:3478/udp    # STUN/TURN non-TLS
     - 5348:5348/tcp    # STUN/TURN TLS
     - 5349:5349/tcp    # STUN/TURN TLS
     - 49500-49800:49500-49800/udp # TURN relay range

    ### Volume mounts - Note: directories/files must be 
    ### (at least) readable by the eturnal user (9000:9000)
    volumes:
      - ./eturnal.yml:/etc/eturnal.yml:ro   # for custom config file
      - ./ACME.185.28.22.166:/opt/eturnal/tls:ro   # for custom tls files
      - ./log_dir:/var/eturnal/logs/log:rw
