
# https://github.com/coturn/coturn
# https://hub.docker.com/r/coturn/coturn

networks:
    traefik:
        external: true

volumes:
    coturn-data:
    coturn-logs:
  
services:
    coturn:
        image: coturn/coturn:latest
        container_name: coturn
        hostname: coturn
        domainname: landingdev.xyz
        user: "999:1001"  # UID 999 (coturn user in container), GID 1000 (coturn group on host)
        networks:
            traefik:
                ipv4_address: 172.20.14.10
                ipv6_address: 2a02:4780:10:e8ad::14:10
        ports:
            # STUN/TURN
            - "3478:3478/udp"  # STUN/TURN signaling
            - "3478:3478/tcp"  # TURN over TCP (optional, for clients behind restrictive firewalls)
            # TLS-TURN          
            - "5349:5349/udp"  # TURN over TLS (DTLS)
            - "5349:5349/tcp"  # TURN over TLS (TCP)
            - "49152-49251:49152-49251/udp"  # Reduced port range for relay
        # Explicitly override timestamp on logfile name
        # command: ["--log-file=/var/log/turnserver.log", "--simple-log"]
        # command: ["turnserver", "--log-file=/var/log/turnserver.log", "--no-log-timestamp"]
        volumes:
            - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
            - ./certs/landingdev.xyz.pem:/etc/ssl/certs/cert.pem:ro
            - ./certs/landingdev.xyz.key:/etc/coturn/privKey.pem:ro
            - "coturn-data:/var/lib/coturn"
            - ./logs:/var/log
            - ./run:/var/run # writing pid file
        environment:
            - DETECT_EXTERNAL_IP=yes
            - DETECT_RELAY_IP=yes
        labels:
            - "traefik.enable=true"
        # labels:
        #    - traefik.enable=true
        #    - traefik.http.routers.coturn.rule=Host(`coturn.landingdev.xyz`)            
        #     - "traefik.udp.routers.coturn.entrypoints=coturn-udp"
        #     - "traefik.udp.services.coturn.loadbalancer.server.port=3478"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "turnadmin", "-c", "/etc/coturn/turnserver.conf", "-check"]
            interval: 30s
            timeout: 10s
            retries: 3

