networks:
  wireguard_network:
    external: true

services:
  wireguard_client3:
    image: linuxserver/wireguard
    container_name: wireguard_client3
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./wg_client3_config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - wireguard_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wg", "show"]
      interval: 30s
      timeout: 10s
      retries: 3


  webapp3:  # App sharing spoke 2's network (VPN IP 10.13.13.4)
    image: traefik/whoami:latest
    container_name: webapp3
    depends_on:
      - wireguard_client3
    network_mode: service:wireguard_client3
    restart: unless-stopped
