networks:
  npm_net:
    external: true

services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    hostname: livekit
    domainname: landingdev.xyz
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   # LIVEKIT
    #   - "7880:7880"
    #   - "7881:7881"
    #   # COTURN
    #   - "3478:3478"
    #   - "3478:3478/udp"
    #   # match port range in livekit.yaml
    #   - "49500-50100:49500-50100/udp"
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    networks:
      npm_net:
        ipv4_address: 10.10.20.30
        ipv6_address: fd12:3456:789a::20:30
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
      - ./acme_lego/certificates/:/opt/certs
    environment:
      - LIVEKIT_API_KEY="Nm7MFqEdn7dEkLW"
      - LIVEKIT_API_SECRET="cpCc17rcrz9TpfG7b0xD2ImsPAMF2P8GP3aqBqlsNLNG"
      - LIVEKIT_PORT=7880
      - LIVEKIT_RTC_TCP_PORT=7881
      - LIVEKIT_REDIS_ADDRESS=redis:6379
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:7880/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    

