#!/bin/bash
echo -e ""
echo -e "REDIS LOGIN\n"
echo "docker exec -it livekit ash"
echo "apk add redis"
echo "redis-cli -u redis://livekit:livekit@redis:6379"
echo "ping"
echo ""
echo "SUBSCRIBE test-channel"
echo -e ""
echo "THEN IN ANOTHER TERMINAL \"docker exec -it livekit ash\" "
echo -e ""
echo "docker exec -it livekit ash"
echo "redis-cli -u redis://livekit-redis:livekit-redis@livekit-redis:6379"
echo "PUBLISH test-channel \"Hello, this is a test message!\" "
echo ""
echo "VIEW REDIS PUBLISH IN THE OTHER LIVEKIT TERMINAL"
