networks:
    easyhaproxy:
        external: true
        name: easyhaproxy


services:
  haproxy:
    image: byjg/easy-haproxy:4.5.0
    container_name: haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs/haproxy
    environment:
      EASYHAPROXY_DISCOVER: docker
      EASYHAPROXY_SSL_MODE: "loose"
      HAPROXY_CUSTOMERRORS: "true"
      HAPROXY_USERNAME: admin
      HAPROXY_PASSWORD: password
      HAPROXY_STATS_PORT: 1936

    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "1936:1936/tcp"
      - "8080:8080/tcp"

#   container:
#     image: byjg/static-httpserver
#     labels:
#       easyhaproxy.http.redirect_ssl: true
#       easyhaproxy.http.domain: haproxy.landingdev.xyz
#       easyhaproxy.http.port: 80
# 
#       easyhaproxy.https.port: 443
#       easyhaproxy.https.localport: 8080
#       easyhaproxy.https.domain: haproxy.landingdev.xyz
#       easyhaproxy.https.ssl_cert=/certs/haproxy/landingdev.xyz.pem

  container2:
    image: byjg/static-httpserver
    volumes:
      - ./certs:/certs/haproxy
    labels:
      easyhaproxy.http.host: host2.local
      easyhaproxy.http.domain: hap.landingdev.xyz
      easyhaproxy.http.port: 80
      easyhaproxy.http.redirect_ssl: true

      easyhaproxy.https.port: 443
      easyhaproxy.https.localport: 8080
      easyhaproxy.https.host: host2.local
      easyhaproxy.https.domain: hap.landingdev.xyz
      easyhaproxy.https.ssl: true

  whoami:
    image: traefik/whoami:latest
    labels:
      - easyhaproxy.frontend.1.domain=who.landingdev.xyz
      - easyhaproxy.frontend.1.ssl_cert=/certs/haproxy/landingdev.xyz.pem
      - easyhaproxy.frontend.1.port=443
      - easyhaproxy.frontend.1.backend.1.host=who.landingdev.xyz
      - easyhaproxy.frontend.1.backend.1.port=80
