networks:
  npm_net:
    external: true

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    domainname: landingdev.xyz
    restart: unless-stopped
    networks:
      npm_net:
        ipv4_address: 10.10.20.20
        ipv6_address: fd12:3456:789a::20:20
    command: redis-server /opt/redis/redis.conf
    volumes:
      - ./conf/redis.conf:/opt/redis/redis.conf:ro
      - ./conf/users.acl:/opt/redis/users.acl:ro
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-p", "6379", "--user", "livekit", "-a", "livekit", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
