# LATEST NODEBB IMAGE IS AT 
# https://github.com/nodebb/NodeBB/pkgs/container/nodebb

networks:
    traefik:
        external: true

services:
    nodebb:
        image: ghcr.io/nodebb/nodebb:20250801-164836
        container_name: nodebb
        hostname: nodebb
        domainname: landingdev.xyz
        # ports:
        #     - "4567:4567"
        depends_on:
            - mongo
        networks:
            traefik:
                ipv4_address: 172.20.6.10
        labels:
            - traefik.enable=true
            - traefik.http.routers.nodebb.rule=Host(`nodebb.landingdev.xyz`)
            - traefik.http.routers.nodebb.entrypoints=websecure
            - traefik.http.routers.nodebb.tls=true
            - traefik.http.services.nodebb.loadbalancer.server.port=4567

    mongo:
        image: mongo:latest
        container_name: mongo
        # ports:
        #     - "27017:27017"
        environment:
            # mongo-ini.js overrides below environment variables
            MONGO_INITDB_ROOT_USERNAME: nodebb
            MONGO_INITDB_ROOT_PASSWORD: nodebb
            MONGO_INITDB_DATABASE: nodebb
        command: mongod --auth
        networks:
            traefik:
                ipv4_address: 172.20.6.20
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro     
