
services:

  eturnal:
    image: ghcr.io/processone/eturnal:latest-alpine
    container_name: eturnal
    hostname: eturnal
    domainname: landingdev.xyz
    restart: unless-stopped
    user: 9000:9000

    ### security options
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    network_mode: host
        
    ### networking options
    # ports:
    #  - 3478:3478     # STUN/TURN non-TLS
    #  - 3478:3478/udp # STUN/TURN non-TLS
    #  - 5349:5349   # STUN/TURN TLS
    #  - 49500-50500:49500-50500/udp # TURN relay range

    ### Environment variables - information on https://eturnal.net/doc/#Environment_Variables
    # environment:
    #   - ETURNAL_RELAY_IPV4_ADDR=185.28.22.166
    #   - ETURNAL_RELAY_IPV6_ADDR=2a02:4780:10:e8ad::1
    #   - STUN_SERVICE=false
    #   - ETURNAL_SECRET=your-very-long-random-string
    env_file:
      - eturnal.env

    ### Volume mounts - Note: directories/files must be (at least) readable by the eturnal user (9000:9000)
    volumes:
      - ./eturnal.yml:/etc/eturnal.yml:ro # for custom config file
      - ./acme_lego/certificates:/opt/eturnal/tls      # for custom tls files
