networks:
  net:
    external: true

volumes:
  db:

services:
  homeserver:
    image: matrixconduit/matrix-conduit:latest
    container_name: matrix
    
    restart: unless-stopped

    volumes:
      - db:/var/lib/matrix-conduit/

    networks:
      net:
        ipv4_address: 10.10.20.10
        ipv6_address: fd12:3456:789a::20:10
        
    environment:
      CONDUIT_SERVER_NAME: matrix.landingdev.xyz
      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
      CONDUIT_DATABASE_BACKEND: rocksdb
      CONDUIT_PORT: 6167
      CONDUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
      CONDUIT_ALLOW_REGISTRATION: 'true'
      CONDUIT_ALLOW_FEDERATION: 'true'
      CONDUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
      CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
      CONDUIT_MAX_CONCURRENT_REQUESTS: 50
      CONDUIT_ADDRESS: 0.0.0.0
      CONDUIT_CONFIG: '' # Ignore this

    labels:
      - traefik.enable=true
      - traefik.http.routers.matrix.rule=Host(`matrix.landingdev.xyz`)
      - traefik.http.routers.matrix.entrypoints=websecure
      - traefik.http.routers.matrix.tls=true
      - traefik.http.services.matrix.loadbalancer.server.port=6167

  chat:
    image: vectorim/element-web:latest
    container_name: chat

    networks:
      net:
        ipv4_address: 10.10.20.20
        ipv6_address: fd12:3456:789a::20:20

    restart: unless-stopped
    volumes:
      - ./element_config.json:/app/config.json
    depends_on:
      - homeserver
    labels:
        - traefik.enable=true
        - traefik.http.routers.chat.rule=Host(`chat.landingdev.xyz`)
        - traefik.http.routers.chat.entrypoints=websecure
        - traefik.http.routers.chat.tls=true
        - traefik.http.services.chat.loadbalancer.server.port=80
