[global]
server_name = "matrix.landingdev.xyz"
database_backend = "rocksdb"
database_path = "/var/lib/matrix-conduit/"
port = 6167
max_request_size = 20000000

allow_registration = true

registration_token = "hzXhBoczX17pZk5HaYepCyhB4jkQm2D61jMjYEEzbM9yrAGfZRaEy1kweiTzANEu"
CONDUIT_TURN_URIS: '["turn:185.28.22.166?transport=udp", "turn:185.28.22.166?transport=tcp"]'
CONDUIT_TURN_SECRET: "hzXhBoczX17pZk5HaYepCyhB4jkQm2D61jMjYEEzbM9yrAGfZRaEy1kweiTzANEu"

allow_check_for_updates = true
allow_federation = true
enable_lightning_bolt = true
trusted_servers = ["matrix.org"]
max_concurrent_requests = 50
address = "0.0.0.0"

[global.well_known]
server = "matrix.landingdev.xyz:443"
client = "https://matrix.landingdev.xyz"
