volumes:
    synapse_data:
    postgres_data:

networks:
    traefik:
        external: true
        
services:
    synapse:
        image: matrixdotorg/synapse:latest
        container_name: matrix
        hostname: matrix
        domainname: landingdev.xyz
        volumes:
            - ./synapse_data:/data:rw
        environment:
            - SYNAPSE_SERVER_NAME=matrix.landingdev.xyz
            - SYNAPSE_REPORT_STATS=no
            - SYNAPSE_CONFIG_DIR=/data
            # contains the user/pw to postgres
            - SYNAPSE_CONFIG_PATH=/data/homeserver.yml
        depends_on:
            - postgres
        networks:
            traefik:
                ipv4_address: 172.20.10.10
                ipv6_address: 2a02:4780:10:e8ad::10:10
        labels:
            - traefik.enable=true
            - traefik.http.routers.matrix.rule=Host(`matrix.landingdev.xyz`)
            - traefik.http.routers.matrix.entrypoints=websecure
            - traefik.http.routers.matrix.tls=true
            - traefik.http.services.matrix.loadbalancer.server.port=8008


    postgres:
        image: postgres:16
        container_name: postgres
        restart: unless-stopped
        networks:
            traefik:
                ipv4_address: 172.20.10.20
                ipv6_address: 2a02:4780:10:e8ad::10:20
        environment:
          - POSTGRES_USER=synapse
          - POSTGRES_PASSWORD=synapse
          - POSTGRES_DB=synapse
          - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
        volumes:
          - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U synapse"]
            interval: 5s
            timeout: 5s
            retries: 5
