networks:
    traefik:
        external: true

volumes:
    redis-data:

services:
    livekit:
        image: livekit/livekit-server:latest
        # image: livekit/livekit-server:v1.8.4
        container_name: livekit
        hostname: livekit
        domainname: landingdev.xyz
        networks:
            traefik:
                ipv4_address: 172.20.16.10
                ipv6_address: 2a02:4780:10:e8ad::16:10
            #internal:
        ports:
            # - "7880:7880/tcp"
            # - "7881:7881/tcp"
            # - "7882:7882/udp"
            - "50100-50200:50100-50200/udp"
        volumes:
            - ./livekit/livekit.yaml:/etc/livekit.yaml
        command: --config /etc/livekit.yaml
        environment:
            - LIVEKIT_REDIS_ADDRESS=172.20.16.20:6379
            - LIVEKIT_REDIS_USER=livekit
            - LIVEKIT_REDIS_PASSWORD=livekit
        labels:
            - "traefik.enable=true"

            - "traefik.http.routers.livekit.rule=Host(`livekit.landingdev.xyz`) && PathPrefix(`/rtc`)"
            - "traefik.http.routers.livekit.entrypoints=websecure"
            - "traefik.http.routers.livekit.tls=true"
            - "traefik.http.routers.livekit.service=livekit"
            - "traefik.http.routers.livekit.middlewares=websocket@file"  # Changed from websocket@docker to websocket@file
            - "traefik.http.services.livekit.loadbalancer.server.port=7880"
            - "traefik.tcp.routers.livekit-rtc.rule=HostSNI(`livekit.landingdev.xyz`)"
            - "traefik.tcp.routers.livekit-rtc.entrypoints=websecure"
            - "traefik.tcp.routers.livekit-rtc.tls=true"
            - "traefik.tcp.routers.livekit-rtc.service=livekit-rtc"
            - "traefik.tcp.services.livekit-rtc.loadbalancer.server.port=7881"

        restart: unless-stopped
        depends_on:
            - redis

    redis:
        image: redis:latest
        container_name: redis
        networks:
            traefik:
                ipv4_address: 172.20.16.20
        restart: unless-stopped
        # restart: no
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
            - ./redis/users.acl:/usr/local/etc/redis/users.acl:ro
        
