module.exports = {
		httpUnsafeOrigin: 'https://crypt.landingdev.xyz',
		httpSafeOrigin: 'https://cryptpad.landingdev.xyz',

    httpAddress: '0.0.0.0',
    httpPort: 3000,
    websocketPort: 3003,
    inactiveTime: 90,
    archiveRetentionTime: 15,
    accountRetentionTime: 365,
    adminKeys: [],
    filePath: './datastore/',
    archivePath: './data/archive',
    pinPath: './data/pins',
    taskPath: './data/tasks',
    blockPath: './block',
    blobPath: './blob',
    blobStagingPath: './data/blobstage',
    decreePath: './data/decrees',
    logPath: './data/logs',
    logFeedback: false,
    installMethod: 'docker',
    logToStdout: true,
    logLevel: 'debug',
    verbose: false,
};
